### ISSUE TITLE
Bug: Couldn't run the app

### ISSUE THREAD

**Issue by tuo65794** [cis3296s24/receiptify-split-the-bill#19]
After creating the app in Spotify for Developers Dashboard and load the information into config.js.  I open the folder but couldn't run these two lines of command. 
 $ cd authorization_code
$ node app.js

it show me this 

node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'C:\Users\Justin\app.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.1

I also try opening the localhost website and it say it cant be reach

Using Windows 
I expect the app.js to run and I'm able to open the localhost

**Comment by tun82434** [comment]
Sorry for the late response, ensure when you are doing node app.js to change directory to receiptifyv1: cd receiptifyv1
